// Category emoji mappings
export const categoryEmojis: Record<string, string> = {
  // علوم
  'math': '🔢',
  'physics': '⚛️',
  'chemistry': '🧪',
  'biology': '🧬',
  'astronomy': '⭐',
  'geology': '⛰️',
  'medicine': '💊',
  'anatomy': '❤️',
  'psychology': '🧠',
  'philosophy': '📚',
  
  // جغرافيا
  'maps': '🗺️',
  'capitals': '🏛️',
  'flags': '🚩',
  'rivers': '🌊',
  'mountains': '🏔️',
  'deserts': '🏜️',
  'oceans': '🌊',
  'islands': '🏝️',
  'arab-countries': '🌍',
  'european-countries': '🌍',
  'asian-countries': '🌏',
  'african-countries': '🌍',
  'american-countries': '🌎',
  
  // تاريخ
  'islamic-history': '🕌',
  'arab-history': '🏛️',
  'world-history': '📖',
  'ancient-history': '🏺',
  'modern-history': '📡',
  'wars': '⚔️',
  'civilizations': '🏗️',
  'prophets': '📿',
  'companions': '👥',
  'scholars': '🎓',
  
  // دين
  'quran': '📖',
  'hadith': '📜',
  'fiqh': '⚖️',
  'aqeedah': '✨',
  'seerah': '🌙',
  'prayers': '🤲',
  'ramadan': '🌙',
  'hajj': '🕋',
  
  // رياضة
  'football': '⚽',
  'basketball': '🏀',
  'tennis': '🎾',
  'swimming': '🏊',
  'athletics': '🏃',
  'world-cup': '🏆',
  'olympics': '🥇',
  'arab-sports': '🎖️',
  'saudi-league': '🏆',
  'premier-league': '🏆',
  'champions-league': '⭐',
  'mma': '🥊',
  'f1': '🏎️',
  'horse-racing': '🐎',
  
  // فن وترفيه
  'movies': '🎬',
  'arab-movies': '🎭',
  'hollywood': '🎬',
  'series': '📺',
  'arab-series': '📺',
  'anime': '🎨',
  'cartoons': '🎨',
  'music': '🎵',
  'arab-music': '🎤',
  'classical-music': '🎼',
  'actors': '🎭',
  'arab-actors': '🎭',
  'singers': '🎤',
  'arab-singers': '🎤',
  'stand-up': '🎤',
  'comedy': '😂',
  'drama': '🎭',
  'documentaries': '🎥',
  
  // تقنية
  'tech': '💻',
  'computers': '💻',
  'smartphones': '📱',
  'apps': '📲',
  'artificial-intelligence': '🤖',
  'programming': '💾',
  'web-development': '🕸️',
  'cybersecurity': '🔐',
  'gaming': '🎮',
  'esports': '🎮',
  'social-media': '📱',
  'internet': '🌐',
  'cryptocurrency': '₿',
  
  // طعام
  'food': '🍽️',
  'arabic-food': '🍛',
  'fast-food': '🍔',
  'drinks': '🥤',
  'desserts': '🍰',
  'fruits': '🍎',
  'vegetables': '🥗',
  'meat': '🥩',
  'seafood': '🦐',
  'coffee': '☕',
  
  // ألعاب واستجمام
  'games': '🎮',
  'board-games': '♟️',
  'puzzles': '🧩',
  'riddles': '🤔',
  'brain-teaser': '🧠',
  'trivia': '❓',
  'word-games': '🔤',
  'card-games': '🃏',
  
  // عربي وثقافة
  'arabic': '🔤',
  'arabic-literature': '📖',
  'poetry': '✍️',
  'proverbs': '💬',
  'slang': '😄',
  'dialects': '🗣️',
  'customs': '🤝',
  'traditions': '🎭',
  'folklore': '👴',
  
  // تعليم
  'education': '🎓',
  'languages': '🌐',
  'english': '🇬🇧',
  'french': '🇫🇷',
  'spanish': '🇪🇸',
  'german': '🇩🇪',
  'chinese': '🇨🇳',
  'japanese': '🇯🇵',
  
  // صحة ولياقة
  'health': '💪',
  'fitness': '🏋️',
  'nutrition': '🥗',
  'wellness': '🧘',
  'first-aid': '🚑',
  
  // ملازي متنوعة
  'general-knowledge': '📚',
  'fun-facts': '💡',
  'celebrities': '🌟',
  'money': '💰',
  'business': '💼',
  'economy': '📈',
  'politics': '🏛️',
  'environment': '🌱',
  'animals': '🦁',
  'nature': '🌿',
  'weather': '🌦️',
  'special-events': '🎉',
  'holidays': '🎄',
  'culture-shock': '😱',
  'religion': '🕌',
  'fashion': '👗',
  'beauty': '💄',
  'travel': '✈️',
  'tourism': '🗼',
  'adventure': '🏔️',
  'transportation': '🚗',
  'military': '🪖',
  'museums': '🎨',
  'libraries': '📚',
  'universities': '🎓',
  'research': '🔬',
  'science': '🧪',
  'technology-news': '📰',
  'recent-events': '📰',
  'entertainment-news': '📺',
  'sports-news': '📰',
  
  // Default
  'default': '❓',
  'other': '📚',
  'custom': '✨',
}

export const getEmojiForCategory = (categoryId: string): string => {
  return categoryEmojis[categoryId] || categoryEmojis['default']
}
